// ═══ AUTO-GENERATED BY PIPELINE — DO NOT EDIT ═══
// Generated: 2026-05-10 16:40:58
// Re-run pipeline.py to update this data with latest scrapes

const PIPELINE_META = {
  "generated_at": "2026-05-10 16:40:58",
  "total_schemes": 24,
  "total_beneficiaries_lakh": 678.8,
  "total_budget_crore": 151976,
  "sectors": 7,
  "avg_impact": 6.8,
  "avg_reach": 54,
  "live_matched": 6,
  "scrape_summary": {
    "sspy_pensions": {
      "status": "UNKNOWN",
      "source": "sspy-up.gov.in"
    },
    "mksy": {
      "status": "SCRAPED",
      "source": "mksy.up.gov.in"
    },
    "pmay_rural": {
      "status": "SCRAPED",
      "source": "rhreporting.nic.in"
    },
    "pmay_urban": {
      "status": "SCRAPED",
      "source": "pmaymis.gov.in"
    },
    "odop": {
      "status": "SCRAPED",
      "source": "odopup.in"
    },
    "ayushman": {
      "status": "SCRAPED",
      "source": "ayushmanup.in"
    },
    "up_gov": {
      "status": "SCRAPED",
      "source": "up.gov.in"
    },
    "scholarship": {
      "status": "FAILED",
      "source": "scholarship.up.gov.in"
    }
  }
};

const SCHEMES = [
  {
    "name": "Mukhyamantri Kanya Sumangala Yojana",
    "short": "",
    "sector": "Women & Girl Child",
    "launch_year": 2019,
    "beneficiaries_lakh": 26.81,
    "budget_crore": 1200,
    "per_person_benefit": "₹25,000 (6 installments birth to graduation)",
    "target_group": "Girl children from economically weaker families",
    "description": "Financial assistance to girl children in 6 stages from birth to graduation to promote health, education & gender equality.",
    "achievements": [
      "26.81 lakh girls benefited by 2026",
      "Amount increased from ₹15,000 to ₹25,000 in 2024-25",
      "3-5 lakh new applicants annually after revision",
      "DBT directly to bank accounts"
    ],
    "challenges": [
      "Awareness gaps in remote areas",
      "Document verification delays"
    ],
    "verdict": "Success",
    "impact_score": 8.5,
    "reach_percent": 72,
    "live_data": true,
    "live_source": "mksy.up.gov.in"
  },
  {
    "name": "Mukhyamantri Samuhik Vivah Yojana",
    "short": "",
    "sector": "Women & Girl Child",
    "launch_year": 2017,
    "beneficiaries_lakh": 3.5,
    "budget_crore": 600,
    "per_person_benefit": "₹51,000 per couple (increased over years)",
    "target_group": "Economically weaker section brides",
    "description": "Financial assistance for mass weddings covering expenses for brides from economically weaker sections.",
    "achievements": [
      "3.5 lakh+ couples benefited",
      "Assistance increased from ₹35,000 to ₹51,000",
      "Reduced dowry burden on poor families"
    ],
    "challenges": [
      "Limited reach in urban areas",
      "Processing delays"
    ],
    "verdict": "Success",
    "impact_score": 7.5,
    "reach_percent": 55,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Mission Shakti",
    "short": "",
    "sector": "Women & Girl Child",
    "launch_year": 2020,
    "beneficiaries_lakh": 50.0,
    "budget_crore": 3146,
    "per_person_benefit": "Multi-program umbrella scheme",
    "target_group": "All women and girls of UP",
    "description": "Umbrella initiative for women safety, dignity & empowerment through multiple sub-schemes.",
    "achievements": [
      "50,000+ BC Sakhis appointed for rural banking",
      "Pink toilets & Mission Shakti centres at police stations",
      "Self-defense training to lakhs of women",
      "Budget rose to ₹3,146 Cr in 2024-25"
    ],
    "challenges": [
      "Ground-level implementation varies by district",
      "Awareness in rural pockets"
    ],
    "verdict": "Success",
    "impact_score": 8.0,
    "reach_percent": 60,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Old Age Pension Scheme (SSPY)",
    "short": "",
    "sector": "Social Security",
    "launch_year": 2016,
    "beneficiaries_lakh": 55.99,
    "budget_crore": 6700,
    "per_person_benefit": "₹1,000/month",
    "target_group": "Citizens aged 60+ years",
    "description": "Monthly financial assistance to eligible senior citizens through Aadhaar-based DBT.",
    "achievements": [
      "55.99 lakh elderly beneficiaries in 2024-25",
      "Target raised to 67.50 lakh for 2025-26",
      "1.77 lakh fake/deceased beneficiaries removed in 2024",
      "Aadhaar-based real-time authentication"
    ],
    "challenges": [
      "Pension amount still low for survival",
      "Delayed disbursements in some quarters"
    ],
    "verdict": "Success",
    "impact_score": 8.0,
    "reach_percent": 78,
    "live_data": true,
    "live_source": "sspy-up.gov.in"
  },
  {
    "name": "Widow Pension Scheme (Nirashrit Mahila)",
    "short": "",
    "sector": "Social Security",
    "launch_year": 2016,
    "beneficiaries_lakh": 29.03,
    "budget_crore": 3500,
    "per_person_benefit": "₹1,000/month",
    "target_group": "Destitute widows",
    "description": "Monthly financial support to destitute widows through DBT.",
    "achievements": [
      "29.03 lakh beneficiaries by Q3 2024-25",
      "Steady increase from 26.12L (Q1) to 29.03L (Q3)",
      "Direct benefit transfer to bank accounts"
    ],
    "challenges": [
      "Many eligible women unaware",
      "₹1,000 insufficient in urban areas"
    ],
    "verdict": "Moderate Success",
    "impact_score": 7.0,
    "reach_percent": 65,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Divyang Pension Scheme",
    "short": "",
    "sector": "Social Security",
    "launch_year": 2016,
    "beneficiaries_lakh": 12.0,
    "budget_crore": 1440,
    "per_person_benefit": "₹1,000/month",
    "target_group": "Persons with disabilities (40%+)",
    "description": "Monthly support to persons with disabilities through Aadhaar-linked DBT.",
    "achievements": [
      "~12 lakh disabled persons covered",
      "Multiple pension amount revisions upward",
      "Integrated with SSPY portal"
    ],
    "challenges": [
      "Disability certificate process cumbersome",
      "Low awareness among target group"
    ],
    "verdict": "Moderate Success",
    "impact_score": 6.5,
    "reach_percent": 50,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Rashtriya Parivarik Laabh Yojana",
    "short": "",
    "sector": "Social Security",
    "launch_year": 2016,
    "beneficiaries_lakh": 5.0,
    "budget_crore": 1500,
    "per_person_benefit": "₹30,000 per family (on breadwinner death)",
    "target_group": "BPL families who lost primary breadwinner",
    "description": "One-time financial aid to BPL families upon death of primary earner.",
    "achievements": [
      "~5 lakh families assisted",
      "Amount at ₹30,000 per family",
      "Online application process"
    ],
    "challenges": [
      "Amount too low for family sustenance",
      "Verification delays up to 6 months",
      "Many eligible families unaware"
    ],
    "verdict": "Mixed",
    "impact_score": 5.0,
    "reach_percent": 35,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "UP Kisan Rin Mochan Yojana (Loan Waiver)",
    "short": "",
    "sector": "Agriculture",
    "launch_year": 2017,
    "beneficiaries_lakh": 86.0,
    "budget_crore": 36000,
    "per_person_benefit": "Up to ₹1,00,000 loan waiver",
    "target_group": "Small & marginal farmers with crop loans",
    "description": "Waiver of agricultural loans up to ₹1 lakh for small and marginal farmers.",
    "achievements": [
      "86 lakh farmers targeted",
      "₹36,000 Cr allocated for waivers",
      "Relief to heavily indebted farmers"
    ],
    "challenges": [
      "Many farmers reported not receiving waiver",
      "Only institutional loans covered, not informal debt",
      "Did not address root causes of farm distress",
      "Beneficiary selection criteria questioned"
    ],
    "verdict": "Mixed",
    "impact_score": 5.5,
    "reach_percent": 45,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Mukhyamantri Krishak Durghatna Kalyan Yojana",
    "short": "",
    "sector": "Agriculture",
    "launch_year": 2019,
    "beneficiaries_lakh": 2.0,
    "budget_crore": 600,
    "per_person_benefit": "₹5-9 lakh (accident/death compensation)",
    "target_group": "Farmers injured/killed during agricultural activities",
    "description": "Financial aid to farmer families for accidental death or disability during farming.",
    "achievements": [
      "~2 lakh families compensated",
      "Compensation up to ₹9 lakh for death",
      "Covers permanent & partial disability"
    ],
    "challenges": [
      "Claim process is slow",
      "Documentation requirements are heavy"
    ],
    "verdict": "Moderate Success",
    "impact_score": 6.0,
    "reach_percent": 40,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Kisan Uday Yojana (Solar Pumps)",
    "short": "",
    "sector": "Agriculture",
    "launch_year": 2018,
    "beneficiaries_lakh": 1.5,
    "budget_crore": 800,
    "per_person_benefit": "Free energy-efficient pump replacement",
    "target_group": "Farmers with old diesel/electric irrigation pumps",
    "description": "Replacement of inefficient irrigation pumps with energy-efficient solar pumps.",
    "achievements": [
      "Limited rollout compared to target",
      "Some farmers received solar pump sets",
      "Aimed to reduce electricity subsidy burden"
    ],
    "challenges": [
      "Very slow implementation",
      "Target was 10 lakh pumps, achieved ~1.5 lakh",
      "Supply chain and installation delays",
      "Maintenance support lacking"
    ],
    "verdict": "Underperformed",
    "impact_score": 3.5,
    "reach_percent": 15,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Kisan Asaan Kist Yojana",
    "short": "",
    "sector": "Agriculture",
    "launch_year": 2018,
    "beneficiaries_lakh": 8.0,
    "budget_crore": 400,
    "per_person_benefit": "Easy installment for electricity bills",
    "target_group": "Farmers with pending electricity dues",
    "description": "Allows farmers to pay pending electricity bills in easy installments.",
    "achievements": [
      "~8 lakh farmers enrolled",
      "Reduced burden of lump-sum electricity payments"
    ],
    "challenges": [
      "Does not reduce electricity cost",
      "Many farmers still default",
      "Band-aid solution"
    ],
    "verdict": "Mixed",
    "impact_score": 4.5,
    "reach_percent": 30,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "One District One Product (ODOP)",
    "short": "",
    "sector": "Employment & Industry",
    "launch_year": 2018,
    "beneficiaries_lakh": 25.0,
    "budget_crore": 6000,
    "per_person_benefit": "Toolkits, training, market access, loans",
    "target_group": "Local artisans, MSME, craftspeople across 75 districts",
    "description": "Flagship initiative promoting indigenous industries and local crafts in every district.",
    "achievements": [
      "ODOP exports reached ₹93,000 Cr by 2024",
      "1.25 lakh modern toolkits distributed",
      "Projects worth ₹6,000 Cr sanctioned under Margin Money Scheme",
      "Budget increased from ₹307 Cr to ₹337 Cr (2025-26)",
      "International recognition and export growth"
    ],
    "challenges": [
      "Quality standardization needed",
      "Marketing support inconsistent across districts"
    ],
    "verdict": "Major Success",
    "impact_score": 9.0,
    "reach_percent": 80,
    "live_data": true,
    "live_source": "odopup.in"
  },
  {
    "name": "Sevayojan Portal (Employment Exchange)",
    "short": "",
    "sector": "Employment & Industry",
    "launch_year": 2018,
    "beneficiaries_lakh": 15.0,
    "budget_crore": 150,
    "per_person_benefit": "Job matching, employment fair access",
    "target_group": "Unemployed youth seeking jobs",
    "description": "Digital platform connecting job seekers with employment opportunities and govt employment fairs.",
    "achievements": [
      "Lakhs of youth registered on portal",
      "Regular employment fairs (Rojgar Mela) conducted",
      "Digital bridge between employers and job seekers"
    ],
    "challenges": [
      "Actual job placements much lower than registrations",
      "Most jobs are low-paying contractual",
      "Private sector participation limited",
      "Quality of matches questionable"
    ],
    "verdict": "Mixed",
    "impact_score": 4.5,
    "reach_percent": 25,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "CM Apprenticeship Promotion Scheme (CMAPS)",
    "short": "",
    "sector": "Employment & Industry",
    "launch_year": 2019,
    "beneficiaries_lakh": 3.0,
    "budget_crore": 300,
    "per_person_benefit": "Apprenticeship + stipend supplement",
    "target_group": "Youth seeking industry training",
    "description": "Encourages industries to train youth through apprenticeship with government-supplemented stipend.",
    "achievements": [
      "~3 lakh youth enrolled in apprenticeships",
      "Industry-academia collaboration improved"
    ],
    "challenges": [
      "Low conversion to permanent jobs",
      "Stipend amounts inadequate",
      "Limited industry participation"
    ],
    "verdict": "Mixed",
    "impact_score": 5.0,
    "reach_percent": 20,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Kaushal Satrang / YUVA Hub",
    "short": "",
    "sector": "Employment & Industry",
    "launch_year": 2018,
    "beneficiaries_lakh": 5.0,
    "budget_crore": 500,
    "per_person_benefit": "Skill training across 7 programs",
    "target_group": "Unemployed youth",
    "description": "Umbrella skill development scheme with 7 sub-programs for youth employability.",
    "achievements": [
      "~5 lakh youth trained",
      "Multiple skill centres established"
    ],
    "challenges": [
      "Training quality inconsistent",
      "Employment outcomes not tracked well",
      "Market-relevant skills gap persists",
      "Many centres underutilized"
    ],
    "verdict": "Underperformed",
    "impact_score": 4.0,
    "reach_percent": 18,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Atal Residential Schools (Atal Awasiya Vidyalaya)",
    "short": "",
    "sector": "Education",
    "launch_year": 2021,
    "beneficiaries_lakh": 0.1,
    "budget_crore": 500,
    "per_person_benefit": "Free CBSE residential education + all expenses",
    "target_group": "Children of construction workers & COVID orphans",
    "description": "Free high-quality CBSE residential schools in every division for construction workers' children.",
    "achievements": [
      "18 schools across all divisions",
      "93.15% pass rate in first CBSE Class 10 batch (2026)",
      "100% pass rate in Varanasi & Prayagraj schools",
      "50:50 gender ratio maintained",
      "Smart classrooms, AI & drone tech labs",
      "10,000+ students enrolled"
    ],
    "challenges": [
      "Limited capacity (only 18 schools)",
      "Needs scaling up"
    ],
    "verdict": "Major Success",
    "impact_score": 9.5,
    "reach_percent": 85,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Pre-Matric & Post-Matric Scholarship",
    "short": "",
    "sector": "Education",
    "launch_year": 2016,
    "beneficiaries_lakh": 80.0,
    "budget_crore": 8000,
    "per_person_benefit": "₹3,000-₹15,000/year depending on level",
    "target_group": "SC, OBC, Minority students",
    "description": "Extensive scholarship programs for students from marginalized communities.",
    "achievements": [
      "~80 lakh students benefited annually",
      "Covers tuition, maintenance & other fees",
      "Online portal for application & tracking"
    ],
    "challenges": [
      "Delayed disbursement common",
      "Verification process slow",
      "Some fake applications detected"
    ],
    "verdict": "Success",
    "impact_score": 8.0,
    "reach_percent": 70,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Free School Bag & Uniform Scheme",
    "short": "",
    "sector": "Education",
    "launch_year": 2017,
    "beneficiaries_lakh": 160.0,
    "budget_crore": 2000,
    "per_person_benefit": "Free bags, uniforms, shoes for govt school students",
    "target_group": "Government school students (Class 1-8)",
    "description": "Provides educational essentials to government school students to reduce dropout rates.",
    "achievements": [
      "1.6 Cr students receive materials annually",
      "Reduced financial barrier to education",
      "Helped reduce dropout rates"
    ],
    "challenges": [
      "Quality of materials varies",
      "Delayed distribution in some districts"
    ],
    "verdict": "Success",
    "impact_score": 7.5,
    "reach_percent": 85,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Ayushman Bharat PMJAY (UP Implementation)",
    "short": "",
    "sector": "Health",
    "launch_year": 2018,
    "beneficiaries_lakh": 45.0,
    "budget_crore": 7040,
    "per_person_benefit": "₹5 lakh health insurance/family/year",
    "target_group": "Poor and vulnerable families",
    "description": "Health insurance coverage of ₹5 lakh per family for secondary & tertiary care hospitalization.",
    "achievements": [
      "5.11 Cr+ Ayushman cards issued in UP",
      "45 lakh+ patients treated",
      "5,669 hospitals empanelled (2,948 govt + 2,721 private)",
      "₹7,040 Cr spent on treatments",
      "6.98 lakh tertiary care patients (₹2,557 Cr)",
      "UP is #1 state in scheme implementation"
    ],
    "challenges": [
      "Some hospitals refuse Ayushman patients",
      "Claim settlement delays",
      "Fraud cases detected"
    ],
    "verdict": "Major Success",
    "impact_score": 9.0,
    "reach_percent": 82,
    "live_data": true,
    "live_source": "ayushmanup.in"
  },
  {
    "name": "Mukhyamantri Jan Arogya Yojana",
    "short": "",
    "sector": "Health",
    "launch_year": 2019,
    "beneficiaries_lakh": 10.0,
    "budget_crore": 1200,
    "per_person_benefit": "Supplementary health coverage",
    "target_group": "Families not covered under PMJAY",
    "description": "State-specific health scheme to bridge gaps and provide additional coverage to vulnerable families.",
    "achievements": [
      "~10 lakh families covered additionally",
      "Supplements central Ayushman scheme",
      "Focus on families just above PMJAY cutoff"
    ],
    "challenges": [
      "Overlap confusion with PMJAY",
      "Limited awareness",
      "Budget constraints"
    ],
    "verdict": "Moderate Success",
    "impact_score": 6.0,
    "reach_percent": 35,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "PMAY-Gramin (Rural Housing, UP)",
    "short": "",
    "sector": "Housing",
    "launch_year": 2016,
    "beneficiaries_lakh": 36.38,
    "budget_crore": 45000,
    "per_person_benefit": "₹1.20-1.30 lakh for pucca house construction",
    "target_group": "Rural poor without pucca houses",
    "description": "Providing pucca houses with toilet, electricity & gas connections to rural poor families.",
    "achievements": [
      "36.85 lakh houses targeted",
      "36.56 lakh houses sanctioned",
      "36.38 lakh houses completed",
      "98.7% completion rate",
      "Includes toilet, electricity, LPG connections"
    ],
    "challenges": [
      "Quality of construction varies",
      "Some delays in fund release"
    ],
    "verdict": "Major Success",
    "impact_score": 9.5,
    "reach_percent": 95,
    "live_data": true,
    "live_source": "pmayg.nic.in"
  },
  {
    "name": "PMAY-Urban (Urban Housing, UP)",
    "short": "",
    "sector": "Housing",
    "launch_year": 2016,
    "beneficiaries_lakh": 17.0,
    "budget_crore": 25000,
    "per_person_benefit": "₹1.5-2.67 lakh subsidy for urban housing",
    "target_group": "Urban poor and EWS/LIG families",
    "description": "Housing for urban poor with interest subsidy and construction assistance.",
    "achievements": [
      "21 lakh+ houses sanctioned",
      "17 lakh houses completed and delivered",
      "Significant contribution to Housing For All mission"
    ],
    "challenges": [
      "Urban land availability issues",
      "Slower pace than rural component"
    ],
    "verdict": "Success",
    "impact_score": 8.0,
    "reach_percent": 75,
    "live_data": true,
    "live_source": "pmay-urban.gov.in"
  },
  {
    "name": "BC Sakhi (Banking Correspondent)",
    "short": "",
    "sector": "Women & Girl Child",
    "launch_year": 2020,
    "beneficiaries_lakh": 0.5,
    "budget_crore": 200,
    "per_person_benefit": "₹4,000/month + commission on transactions",
    "target_group": "Rural women for doorstep banking services",
    "description": "Empowering rural women to provide banking services at grassroots level.",
    "achievements": [
      "50,000+ women appointed as BC Sakhis",
      "Doorstep banking in remote villages",
      "Financial inclusion of rural households",
      "Women earn ₹4,000/month + transaction commission"
    ],
    "challenges": [
      "Technology literacy gaps",
      "Network connectivity issues in villages"
    ],
    "verdict": "Success",
    "impact_score": 8.0,
    "reach_percent": 65,
    "live_data": false,
    "live_source": ""
  },
  {
    "name": "Mahila Samarthya Yojana",
    "short": "",
    "sector": "Women & Girl Child",
    "launch_year": 2021,
    "beneficiaries_lakh": 2.0,
    "budget_crore": 200,
    "per_person_benefit": "Skill training & entrepreneurship support",
    "target_group": "Women seeking skill development & self-employment",
    "description": "Focuses on skill development and entrepreneurship promotion for women.",
    "achievements": [
      "~2 lakh women trained",
      "SHG linkages established"
    ],
    "challenges": [
      "Scheme is relatively new",
      "Scale of implementation still small",
      "Impact data not yet comprehensive"
    ],
    "verdict": "Too Early to Judge",
    "impact_score": 5.0,
    "reach_percent": 20,
    "live_data": false,
    "live_source": ""
  }
];
