// ═══ LIVE DATA from dashboard_data.js (auto-generated by pipeline) ═══
// SCHEMES and PIPELINE_META are loaded from dashboard_data.js

const SECTOR_COLORS={"Women & Girl Child":"#ec4899","Social Security":"#f97316","Agriculture":"#22c55e","Employment & Industry":"#3b82f6","Education":"#a855f7","Health":"#06b6d4","Housing":"#ef4444"};
const VERDICT_MAP={"Major Success":{cls:"badge-major",icon:"🏆",color:"#10b981"},"Success":{cls:"badge-success",icon:"✅",color:"#4ade80"},"Moderate Success":{cls:"badge-moderate",icon:"👍",color:"#fbbf24"},"Mixed":{cls:"badge-mixed",icon:"⚠️",color:"#fb923c"},"Underperformed":{cls:"badge-under",icon:"❌",color:"#f87171"},"Too Early to Judge":{cls:"badge-early",icon:"🕐",color:"#94a3b8"}};

// ═══ COUNTER ANIMATION (uses live PIPELINE_META) ═══
function animateCounters(){
  if(typeof PIPELINE_META!=='undefined'){
    const m=PIPELINE_META;
    document.querySelector('#stat-schemes .stat-num').dataset.target=m.total_schemes;
    document.querySelector('#stat-ben .stat-num').dataset.target=(m.total_beneficiaries_lakh/100).toFixed(2);
    document.querySelector('#stat-budget .stat-num').dataset.target=(m.total_budget_crore/100000).toFixed(2);
    document.querySelector('#stat-sectors .stat-num').dataset.target=m.sectors;
    document.querySelector('#stat-score .stat-num').dataset.target=m.avg_impact;
    // Show data freshness
    const ds=document.getElementById('dataStatus');
    if(ds)ds.innerHTML=`<p style="color:#10b981;margin-bottom:8px">🟢 <strong>LIVE DATA</strong> — Last updated: ${m.generated_at} | ${m.live_matched} portals scraped | ${m.total_schemes} schemes</p>`;
  }
  document.querySelectorAll('.stat-num').forEach(el=>{const target=parseFloat(el.dataset.target);const isInt=Number.isInteger(target);let current=0;const step=target/60;const timer=setInterval(()=>{current+=step;if(current>=target){current=target;clearInterval(timer)}el.textContent=isInt?Math.round(current):current.toFixed(2)},25)})
}

// ═══ SECTOR CHARTS ═══
function initSectorCharts(){
  const sectors={};
  SCHEMES.forEach(s=>{if(!sectors[s.sector])sectors[s.sector]={ben:0,bud:0,count:0,impact:0,reach:0};sectors[s.sector].ben+=s.beneficiaries_lakh;sectors[s.sector].bud+=s.budget_crore;sectors[s.sector].count++;sectors[s.sector].impact+=s.impact_score;sectors[s.sector].reach+=s.reach_percent});
  const labels=Object.keys(sectors);const colors=labels.map(l=>SECTOR_COLORS[l]);

  new Chart(document.getElementById('chartSectorBen'),{type:'doughnut',data:{labels,datasets:[{data:labels.map(l=>Math.round(sectors[l].ben)),backgroundColor:colors,borderColor:'#0a0e1a',borderWidth:3}]},options:{responsive:true,plugins:{legend:{position:'bottom',labels:{color:'#94a3b8',padding:12,font:{size:11}}}}}});

  new Chart(document.getElementById('chartSectorBudget'),{type:'bar',data:{labels,datasets:[{data:labels.map(l=>sectors[l].bud),backgroundColor:colors.map(c=>c+'cc'),borderColor:colors,borderWidth:1,borderRadius:6}]},options:{indexAxis:'y',responsive:true,plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#64748b',callback:v=>'₹'+v.toLocaleString()+'Cr'},grid:{color:'#1e293b'}},y:{ticks:{color:'#94a3b8',font:{size:11}},grid:{display:false}}}}});

  new Chart(document.getElementById('chartSectorCompare'),{type:'bar',data:{labels,datasets:[{label:'Avg Impact (/10)',data:labels.map(l=>(sectors[l].impact/sectors[l].count).toFixed(1)),backgroundColor:'#6366f1aa',borderRadius:4},{label:'Avg Reach (%)',data:labels.map(l=>(sectors[l].reach/sectors[l].count/10).toFixed(1)),backgroundColor:'#06b6d4aa',borderRadius:4}]},options:{responsive:true,plugins:{legend:{labels:{color:'#94a3b8'}}},scales:{x:{ticks:{color:'#64748b',font:{size:10}},grid:{display:false}},y:{ticks:{color:'#64748b'},grid:{color:'#1e293b'}}}}});

  // Sector cards
  const container=document.getElementById('sectorCards');
  labels.sort((a,b)=>sectors[b].ben-sectors[a].ben).forEach(s=>{
    const d=sectors[s];const avg_imp=(d.impact/d.count).toFixed(1);const avg_reach=Math.round(d.reach/d.count);
    container.innerHTML+=`<div class="sector-card" style="border-left:3px solid ${SECTOR_COLORS[s]}"><div class="sc-name"><span class="sc-dot" style="background:${SECTOR_COLORS[s]}"></span>${s}</div><div class="sc-row"><span>Schemes</span><span class="sc-val">${d.count}</span></div><div class="sc-row"><span>Beneficiaries</span><span class="sc-val">${d.ben.toFixed(1)}L</span></div><div class="sc-row"><span>Budget</span><span class="sc-val">₹${d.bud.toLocaleString()} Cr</span></div><div class="sc-row"><span>Avg Impact</span><span class="sc-val">${avg_imp}/10</span></div><div class="sc-row"><span>Avg Reach</span><span class="sc-val">${avg_reach}%</span></div></div>`})
}

// ═══ SCHEME CARDS ═══
function renderSchemes(list){
  const grid=document.getElementById('schemeGrid');grid.innerHTML='';
  list.forEach((s,i)=>{
    const v=VERDICT_MAP[s.verdict]||VERDICT_MAP["Mixed"];
    const scoreColor=s.impact_score>=8?'#10b981':s.impact_score>=6?'#fbbf24':'#ef4444';
    grid.innerHTML+=`<div class="scheme-card animate-in" style="animation-delay:${i*0.05}s" onclick="this.classList.toggle('expanded')">
      <div class="sc-header"><div class="sc-title">${s.name}</div><span class="sc-badge ${v.cls}">${v.icon} ${s.verdict}</span></div>
      <div class="sc-sector" style="color:${SECTOR_COLORS[s.sector]}">${s.sector} • Launched ${s.launch_year}</div>
      <div class="sc-desc">${s.description}</div>
      <div class="sc-metrics">
        <div class="sc-metric"><div class="val">${s.beneficiaries_lakh}L</div><div class="lbl">Beneficiaries</div></div>
        <div class="sc-metric"><div class="val">₹${s.budget_crore>=1000?(s.budget_crore/1000).toFixed(1)+'K':s.budget_crore}</div><div class="lbl">Crore Budget</div></div>
        <div class="sc-metric"><div class="val" style="color:${scoreColor}">${s.impact_score}</div><div class="lbl">Impact /10</div></div>
      </div>
      <div class="sc-score-bar"><div class="sc-score-fill" style="width:${s.reach_percent}%;background:${scoreColor}"></div></div>
      <div class="sc-detail"><div class="sc-detail-inner">
        <p style="font-size:12px;color:#64748b">👥 ${s.target_group} • ${s.per_person_benefit}</p>
        <h4>✓ Achievements</h4><ul>${s.achievements.map(a=>`<li>${a}</li>`).join('')}</ul>
        <h4>✗ Challenges</h4><ul>${s.challenges.map(c=>`<li>${c}</li>`).join('')}</ul>
      </div></div>
    </div>`})
}

function initFilters(){
  const sectorSel=document.getElementById('filterSector');
  const verdictSel=document.getElementById('filterVerdict');
  [...new Set(SCHEMES.map(s=>s.sector))].forEach(s=>{sectorSel.innerHTML+=`<option value="${s}">${s}</option>`});
  [...new Set(SCHEMES.map(s=>s.verdict))].forEach(v=>{verdictSel.innerHTML+=`<option value="${v}">${v}</option>`});

  const applyFilters=()=>{
    let list=[...SCHEMES];
    const sec=sectorSel.value,ver=verdictSel.value,q=document.getElementById('searchBox').value.toLowerCase(),sort=document.getElementById('sortBy').value;
    if(sec!=='all')list=list.filter(s=>s.sector===sec);
    if(ver!=='all')list=list.filter(s=>s.verdict===ver);
    if(q)list=list.filter(s=>s.name.toLowerCase().includes(q)||s.description.toLowerCase().includes(q));
    list.sort((a,b)=>b[sort]-a[sort]);
    renderSchemes(list)};

  sectorSel.onchange=verdictSel.onchange=document.getElementById('searchBox').oninput=document.getElementById('sortBy').onchange=applyFilters;
  renderSchemes([...SCHEMES].sort((a,b)=>b.impact_score-a.impact_score))
}

// ═══ VERDICT CHARTS ═══
function initVerdictCharts(){
  const vc={};SCHEMES.forEach(s=>{vc[s.verdict]=(vc[s.verdict]||0)+1});
  new Chart(document.getElementById('chartVerdict'),{type:'pie',data:{labels:Object.keys(vc),datasets:[{data:Object.values(vc),backgroundColor:Object.keys(vc).map(v=>(VERDICT_MAP[v]||{}).color||'#666'),borderColor:'#0a0e1a',borderWidth:2}]},options:{responsive:true,plugins:{legend:{position:'bottom',labels:{color:'#94a3b8',padding:10,font:{size:11}}}}}});

  new Chart(document.getElementById('chartScatter'),{type:'scatter',data:{datasets:Object.keys(SECTOR_COLORS).map(sec=>({label:sec,data:SCHEMES.filter(s=>s.sector===sec).map(s=>({x:s.budget_crore,y:s.impact_score,r:Math.sqrt(s.beneficiaries_lakh)*3,label:s.short})),backgroundColor:SECTOR_COLORS[sec]+'99',borderColor:SECTOR_COLORS[sec],pointRadius:SCHEMES.filter(s=>s.sector===sec).map(s=>Math.max(5,Math.sqrt(s.beneficiaries_lakh)*2))}))},options:{responsive:true,plugins:{legend:{labels:{color:'#94a3b8',font:{size:10}}},tooltip:{callbacks:{label:ctx=>`${ctx.raw.label}: ₹${ctx.raw.x.toLocaleString()}Cr, Impact ${ctx.raw.y}/10`}}},scales:{x:{title:{display:true,text:'Budget (₹ Crore)',color:'#64748b'},ticks:{color:'#64748b'},grid:{color:'#1e293b'}},y:{title:{display:true,text:'Impact Score (/10)',color:'#64748b'},ticks:{color:'#64748b'},grid:{color:'#1e293b'}}}}});

  // Verdict summary cards
  const container=document.getElementById('verdictSummary');
  ["Major Success","Success","Moderate Success","Mixed","Underperformed","Too Early to Judge"].forEach(v=>{
    const items=SCHEMES.filter(s=>s.verdict===v);if(!items.length)return;
    const vm=VERDICT_MAP[v];
    container.innerHTML+=`<div class="verdict-card" style="border-left:3px solid ${vm.color}"><div class="vc-title">${vm.icon} ${v} (${items.length})</div><ul>${items.map(s=>`<li><strong>${s.short}</strong> — ${s.beneficiaries_lakh}L beneficiaries, ${s.impact_score}/10</li>`).join('')}</ul></div>`})
}

// ═══ IMPACT SECTION ═══
function initImpact(){
  const impacts=[
    {icon:"🏠",title:"Housing",text:"53+ lakh pucca houses built. Families got permanent shelter with toilet, electricity & gas connections. Biggest life-changing scheme for homeless families."},
    {icon:"💊",title:"Healthcare",text:"45 lakh+ patients received FREE treatment worth ₹7,040 Cr. 5 Cr+ Ayushman cards issued. Families no longer go bankrupt from medical emergencies."},
    {icon:"👵",title:"Social Security",text:"97+ lakh elderly, widows & disabled receive ₹1,000/month pension. Basic survival support for the most vulnerable sections."},
    {icon:"👧",title:"Girl Child",text:"26.81 lakh girls got ₹25,000 support from birth to graduation. Reduced female foeticide incentive, increased girl education rates."},
    {icon:"🎓",title:"Education",text:"1.6 Cr+ students get free bags & uniforms. 80 lakh+ SC/OBC students get scholarships. Atal schools gave construction workers' children world-class education."},
    {icon:"🌾",title:"Agriculture",text:"86 lakh farmers targeted for loan waiver but impact was mixed. Solar pump scheme achieved only 15% of target. Root causes of farm distress remain."},
    {icon:"💼",title:"Employment",text:"ODOP was a game-changer — ₹93,000 Cr exports, 1.25L toolkits. But employment portals & skill programs underdelivered on actual job creation."},
    {icon:"👩",title:"Women",text:"50,000 BC Sakhis earning via banking. Mission Shakti improved safety. Mass marriage scheme reduced dowry burden on 3.5 lakh families."}
  ];
  const grid=document.getElementById('impactGrid');
  impacts.forEach(imp=>{grid.innerHTML+=`<div class="impact-card"><div class="ic-icon">${imp.icon}</div><div class="ic-title">${imp.title}</div><div class="ic-text">${imp.text}</div></div>`})
}

// ═══ FINDINGS ═══
function initFindings(){
  const findings=[
    {icon:"🏆",text:"<strong>Best Performers:</strong> PMAY Rural (98.7% completion), Atal Schools (93% pass rate), ODOP (₹93K Cr exports), Ayushman Bharat (45L treated)"},
    {icon:"❌",text:"<strong>Underperformers:</strong> Kisan Uday Solar Pumps (15% of target), Kaushal Satrang (poor job outcomes), Sevayojan (low placement rates)"},
    {icon:"⚠️",text:"<strong>Mixed Results:</strong> Kisan Rin Mochan loan waiver was politically popular but many farmers reported non-receipt. Only institutional loans covered."},
    {icon:"📈",text:"<strong>Biggest Reach:</strong> Free Bags & Uniform (1.6 Cr students), Scholarships (80L students), Old Age Pension (56L elderly)"},
    {icon:"💰",text:"<strong>Biggest Budget:</strong> PMAY Rural (₹45,000 Cr), Loan Waiver (₹36,000 Cr), PMAY Urban (₹25,000 Cr)"},
    {icon:"🎯",text:"<strong>Highest Impact:</strong> Atal Schools (9.5/10), PMAY Rural (9.5/10), ODOP (9.0/10), Ayushman Bharat (9.0/10)"},
    {icon:"📊",text:"<strong>Overall:</strong> 67% of schemes performed well (Success+), 21% had mixed results, 8% underperformed, 4% too early to judge"}
  ];
  const grid=document.getElementById('findingsGrid');
  findings.forEach(f=>{grid.innerHTML+=`<div class="finding-card"><div class="fc-icon">${f.icon}</div><div class="fc-text">${f.text}</div></div>`})
}

// ═══ INIT ═══
document.addEventListener('DOMContentLoaded',()=>{
  animateCounters();initSectorCharts();initFilters();initVerdictCharts();initImpact();initFindings();
  // Intersection observer for animations
  const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.style.opacity='1'})},{threshold:0.1});
  document.querySelectorAll('.section').forEach(s=>obs.observe(s))
});
